#!/usr/bin/env node
// Build script: concatenates the modular source files in src/ into a single,
// self-contained dist/index.html — no bundler, no external dependencies.
// This keeps the shippable artifact exactly what it always was (one HTML file
// you can open directly in a browser, no server needed) while letting the
// source itself live as separate, individually-editable files.
"use strict";
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src');
const JS_DIR = path.join(SRC, 'js');
const OUT_DIR = path.join(__dirname, 'dist');
const OUT_FILE = path.join(OUT_DIR, 'index.html');
// docs/index.html is a duplicate copy for GitHub Pages, which (without a workflow-based
// deploy) can only serve from a branch's root or /docs folder — so we mirror the build
// output there too, kept in sync automatically on every `npm run build`.
const PAGES_DIR = path.join(__dirname, 'docs');
const PAGES_FILE = path.join(PAGES_DIR, 'index.html');

function read(p){ return fs.readFileSync(p, 'utf8'); }

const shell = read(path.join(SRC, 'shell.html'));
const style = read(path.join(SRC, 'style.css'));
const body = read(path.join(SRC, 'body.html'));

// config.json holds runtime-tunable settings (spectator mode delay, etc). It's inlined
// as a JS constant at build time — not fetched at runtime — because dist/index.html
// must stay a single file openable via file:// with no server (fetch() of local JSON
// is blocked by browsers under file://).
const config = JSON.parse(read(path.join(SRC, 'config.json')));
const configScript = `/* ---- src/config.json ---- */\nconst GAME_CONFIG = ${JSON.stringify(config, null, 2)};`;

// JS modules are concatenated in filename order (01-, 02-, ... prefixes make the
// dependency order explicit and stable — see src/js/README.md for what each does).
const jsFiles = fs.readdirSync(JS_DIR).filter(f => f.endsWith('.js')).sort();
if (jsFiles.length === 0) {
  console.error('No JS modules found in ' + JS_DIR);
  process.exit(1);
}
// ---- Core ----
// The rules, AI and map model: the part of the game that also runs on the server. It must not
// depend on the browser, so the build stops if a core file mentions a browser global or a
// function/variable that only a UI file declares (the `host` hooks are the one way out).
const CORE_FILES = ['00-core-utils.js', '02-map-model.js', '04-game-state.js', '04b-actions.js', '05-ai.js'];
const BROWSER_GLOBALS = ['document', 'window', 'localStorage', 'navigator', 'requestAnimationFrame',
  'alert', 'confirm', 'Blob', 'URL', 'performance'];
const TOP_LEVEL_DECL = /^(?:async\s+)?function\s+(\w+)|^(let|const|var)\s+(\w+)/gm;
function stripCommentsAndStrings(src){
  return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '')
    .replace(/`(?:\\.|[^`\\])*`/g, '``').replace(/'(?:\\.|[^'\\\n])*'/g, "''").replace(/"(?:\\.|[^"\\\n])*"/g, '""');
}
function checkCoreIsBrowserFree(){
  const uiNames = {};
  jsFiles.filter(f => !CORE_FILES.includes(f)).forEach(f => {
    for (const m of read(path.join(JS_DIR, f)).matchAll(TOP_LEVEL_DECL)) uiNames[m[1] || m[3]] = f;
  });
  const problems = [];
  CORE_FILES.forEach(f => {
    const code = stripCommentsAndStrings(read(path.join(JS_DIR, f)));
    // identifiers that aren't a property access (`host.renderGame`) or an object key (`renderGame(){}`, `x:`)
    for (const m of code.matchAll(/(?<![.\w$])([A-Za-z_$][\w$]*)(?!\s*(?:\([^)]*\)\s*\{|:))/g)) {
      const name = m[1];
      if (uiNames[name]) problems.push(`${f}: uses ${name} (declared in ${uiNames[name]})`);
      else if (BROWSER_GLOBALS.includes(name)) problems.push(`${f}: uses browser global ${name}`);
    }
  });
  if (problems.length) {
    console.error('Core files must not depend on the browser/UI:\n  ' + [...new Set(problems)].join('\n  '));
    process.exit(1);
  }
}
for (const f of CORE_FILES) {
  if (!jsFiles.includes(f)) { console.error('Missing core file ' + f); process.exit(1); }
}
checkCoreIsBrowserFree();

// dist/core.js: the core files as one CommonJS module for Node (server, tests).
//   const core = require('./dist/core.js')(config, hostHooks);
// Every top-level function of the core is a property of `core`; its top-level `let` state
// (game, mapData, RUNTIME_CONFIG, …) is readable and assignable through it.
function buildCoreModule(){
  const sources = CORE_FILES.map(f => `/* ---- src/js/${f} ---- */\n${read(path.join(JS_DIR, f)).replace(/\s+$/, '')}`);
  const fns = [], vars = [], consts = [];
  CORE_FILES.forEach(f => {
    for (const m of read(path.join(JS_DIR, f)).matchAll(TOP_LEVEL_DECL)) {
      if (m[1]) fns.push(m[1]); else if (m[2] === 'const') consts.push(m[3]); else vars.push(m[3]);
    }
  });
  const exportsSrc = [
    ...fns.map(n => `  ${n},`),
    ...consts.map(n => `  ${n},`),
    ...vars.map(n => `  get ${n}(){ return ${n}; }, set ${n}(v){ ${n} = v; },`),
  ].join('\n');
  return `// GENERATED by build.js from src/js (${CORE_FILES.join(', ')}) — do not edit.
"use strict";
module.exports = function createCore(GAME_CONFIG, hostHooks){

${sources.join('\n\n')}

if(hostHooks) Object.assign(host, hostHooks);
return {
${exportsSrc}
};
};
`;
}

const script = [configScript].concat(jsFiles.map(f => {
  const content = read(path.join(JS_DIR, f)).replace(/\s+$/, '');
  return `/* ---- src/js/${f} ---- */\n${content}`;
})).join('\n\n');

// A syntax error in any module would otherwise only show up as a dead page in the browser.
try { new (require('vm').Script)('(function(){"use strict";\n' + script + '\n})', { filename: 'bundle.js' }); }
catch (e) { console.error('Syntax error in the bundled script: ' + e.message + '\n' + String(e.stack).split('\n').slice(0, 4).join('\n')); process.exit(1); }

let out = shell
  .replace('__STYLE__', () => style.replace(/\s+$/, ''))
  .replace('__BODY__', () => body.replace(/\s+$/, ''))
  .replace('__SCRIPT__', () => script);

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, out, 'utf8');
fs.mkdirSync(PAGES_DIR, { recursive: true });
fs.writeFileSync(PAGES_FILE, out, 'utf8');
const CORE_OUT = path.join(OUT_DIR, 'core.js');
fs.writeFileSync(CORE_OUT, buildCoreModule(), 'utf8');
console.log(`Built core module ${CORE_OUT}.`);
console.log(`Built ${OUT_FILE} and ${PAGES_FILE} from ${jsFiles.length} JS modules (${out.length} bytes).`);
